
Merge into dbo.FormRoleMapping AS Target 
USING (
	SELECT 1, 1 UNION ALL
	SELECT 1, 2 UNION ALL
	SELECT 1, 3 UNION ALL
	SELECT 1, 4 UNION ALL
	SELECT 1, 5 UNION ALL
	SELECT 1, 6 UNION ALL
	SELECT 1, 7 UNION ALL
	SELECT 1, 8 UNION ALL
	SELECT 1, 9 UNION ALL
	SELECT 1, 10 UNION ALL
	SELECT 1, 11 UNION ALL
	SELECT 1, 12 UNION ALL
	SELECT 1, 13 UNION ALL
	SELECT 3, 14 UNION ALL
	SELECT 3, 15 UNION ALL
	SELECT 3, 16 UNION ALL
	SELECT 4, 14 UNION ALL
	SELECT 4, 15 UNION ALL
	SELECT 4, 16 UNION ALL
	SELECT 1003, 17 UNION ALL
	SELECT 1005, 14 UNION ALL
	SELECT 1005, 15 UNION ALL
	SELECT 1005, 16 UNION ALL
	SELECT 4, 18 UNION ALL
	SELECT 4, 19 UNION ALL
	SELECT 3, 18 UNION ALL
	SELECT 3, 19
)
AS Source (RoleId, FormID)
ON Target.RoleId = Source.RoleId
WHEN MATCHED THEN 
UPDATE SET 
	FormID = Source.FormID

WHEN NOT MATCHED BY TARGET THEN 
INSERT (RoleId, FormID) 
VALUES (RoleId, FormID);